FROM debian:testing
ARG         DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y dist-upgrade

RUN apt-get update && apt-get install --yes --no-install-recommends \
  adduser \
  build-essential \
  automake \
  pandoc \
  python3-all \
  git \
  ghc \
  ghc-ghci \
  cabal-install \
  libghc-cabal-dev \
  libghc-case-insensitive-dev \
  libghc-curl-dev \
  libghc-json-dev \
  libghc-snap-server-dev \
  libghc-network-dev \
  libghc-parallel-dev \
  libghc-utf8-string-dev \
  libghc-deepseq-dev \
  libghc-hslogger-dev \
  libghc-cryptonite-dev \
  libghc-text-dev \
  libghc-hinotify-dev \
  libghc-base64-bytestring-dev \
  libghc-zlib-dev \
  libghc-regex-pcre2-dev libpcre2-dev \
  libghc-regex-tdfa-dev \
  libghc-attoparsec-dev \
  libghc-vector-dev \
  libghc-lifted-base-dev \
  libghc-lens-dev \
  libghc-psqueue-dev \
  libghc-test-framework-quickcheck2-dev \
  libghc-test-framework-hunit-dev \
  libghc-temporary-dev \
  libghc-old-time-dev \
  black \
  pylint \
  python3-bitarray \
  python3-mock \
  python3-openssl \
  python3-paramiko \
  python3-pycurl \
  python3-pyinotify \
  python3-pyparsing \
  python3-pytest \
  python3-simplejson \
  python3-sphinx \
  python3-yaml \
  python3-pip \
  graphviz \
  openssh-client \
  procps \
  qemu-utils \
  socat \
  iproute2 && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN groupadd -r build && useradd -r -g build build
