name: Publish Ganeti CI Docker images
on:
  push:
    branches: [master]
  schedule:
    - cron: "42 1 * * 3"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push ${{ matrix.image-name }}-py3 image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-name: [bookworm, debian-testing, focal, jammy, noble]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          dockerfile: ganeti/Dockerfile.${{ matrix.image-name }}
          tags: ${{ matrix.image-name }}-py3
          username: apoikos
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ganeti/ci
